/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AsteriskRouteImport } from './routes/asterisk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResearchRouteImport } from './routes/api/research'

const AsteriskRoute = AsteriskRouteImport.update({
  id: '/asterisk',
  path: '/asterisk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asterisk': typeof AsteriskRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asterisk': typeof AsteriskRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asterisk': typeof AsteriskRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asterisk' | '/api/research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asterisk' | '/api/research'
  id: '__root__' | '/' | '/asterisk' | '/api/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsteriskRoute: typeof AsteriskRoute
  ApiResearchRoute: typeof ApiResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/asterisk': {
      id: '/asterisk'
      path: '/asterisk'
      fullPath: '/asterisk'
      preLoaderRoute: typeof AsteriskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsteriskRoute: AsteriskRoute,
  ApiResearchRoute: ApiResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
